src/Entity/SATProduto.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="sat_produto",indexes={@ORM\Index(name="idproduto_idx", columns={"id_Produto"})})
 */
Class SATProduto
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     *
     */
    private $idProduto;
    /**
     * @ORM\Column(type="datetime")
     */
    private $dataInclusao;
    private $codigo;
    private $descricao;
    private $origem;
    /**
     * @Assert\Length(
     *     min="8",
     *     minMessage="NCM menor do que {{ limit }} caracteres"
     * )
     *
     * @Assert\NotEqualTo(
     *     value="00000000",
     *     message="NCM não pode ser igual a {{ compared_value }}"
     * )
     */
    private $ncm;

    /**
     * @Assert\EqualTo(
     *     value="49",
     *     message="Valor diferente de {{ compared_value }}")
     */
    private $pis;
    /**
     * @Assert\EqualTo(
     *     value="49",
     *     message="Valor diferente de {{ compared_value }}")
     */
    private $cofins;
    private $simples_csosn;
    /**
     * @Assert\Choice({"TR", "FF","NN","II"}, message="Tipo de tributação {{ value }} é inválido")
     */
    private $tributacao;


    /**
     * @Assert\Choice({"18", "25", "12"}, message="Valor de ICMS {{ value }} é inválido")
     */
    private $icms;

    /**
     * @return mixed
     */
    public function getIdProduto()
    {
        return $this->idProduto;
    }

    /**
     * @param mixed $idProduto
     */
    public function setIdProduto($idProduto)
    {
        $this->idProduto = $idProduto;
    }

    /**
     * @return mixed
     */
    public function getDataInclusao()
    {
        return $this->dataInclusao;
    }

    /**
     * @param mixed $dataInclusao
     */
    public function setDataInclusao($dataInclusao)
    {
        $this->dataInclusao = $dataInclusao;
    }

    /**
     * @return mixed
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * @param mixed $codigo
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;
    }

    /**
     * @return mixed
     */
    public function getDescricao()
    {
        return $this->descricao;
    }

    /**
     * @param mixed $descricao
     */
    public function setDescricao($descricao)
    {
        $this->descricao = $descricao;
    }

    /**
     * @return mixed
     */
    public function getOrigem()
    {
        return $this->origem;
    }

    /**
     * @param mixed $origem
     */
    public function setOrigem($origem)
    {
        $this->origem = $origem;
    }

    /**
     * @return mixed
     */
    public function getNcm()
    {
        return $this->ncm;
    }

    /**
     * @param mixed $ncm
     */
    public function setNcm($ncm)
    {
        $this->ncm = $ncm;
    }

    /**
     * @return mixed
     */
    public function getPis()
    {
        return $this->pis;
    }

    /**
     * @param mixed $pis
     */
    public function setPis($pis)
    {
        $this->pis = $pis;
    }

    /**
     * @return mixed
     */
    public function getCofins()
    {
        return $this->cofins;
    }

    /**
     * @param mixed $cofins
     */
    public function setCofins($cofins)
    {
        $this->cofins = $cofins;
    }

    /**
     * @return mixed
     */
    public function getSimplesCsosn()
    {
        return $this->simples_csosn;
    }

    /**
     * @param mixed $simples_csosn
     */
    public function setSimplesCsosn($simples_csosn)
    {
        $this->simples_csosn = $simples_csosn;
    }

    /**
     * @return mixed
     */
    public function getTributacao()
    {
        return $this->tributacao;
    }

    /**
     * @param mixed $tributacao
     */
    public function setTributacao($tributacao)
    {
        $this->tributacao = $tributacao;
    }

    /**
     * @return mixed
     */
    public function getIcms()
    {
        return $this->icms;
    }

    /**
     * @param mixed $icms
     */
    public function setIcms($icms)
    {
        $this->icms = $icms;
    }


}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {


        return $this->render('default/page_blank.twig',array());
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block page_content %}
    {{ include("default/page_principal.html.twig") }}
{% endblock %}


 {% block javascripts %}
 {% endblock %}

templates/default/page_ajuste_saldos_estoque.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Ajuste de Saldos de Estoque</h3>
                </div>

            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Produtos</h2>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="table-responsive table-striped">
                                <table id="produto" class="table ">
                                    <thead>
                                    <tr>

                                        <th>ID</th>
                                        <th>Código</th>
                                        <th>Descrição</th>
                                        <th>Saldo</th>

                                    </tr>
                                    </thead>
                                    <tbody id="tbline">


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


 {% block javascripts %}
     <script type="text/javascript">

         $(document).ready(function () {
             $.ajax({
                 url: "/estoque/saldos/ajax",
                 type: "POST",
                 data: {
                     'CODIGO': ''
                 },
                 success: function (resposta) {
                     var tbody = document.getElementById('tbline');
                     var table = document.getElementsByTagName("table")[0];

                     for (i = 0; i < resposta.produtos.length; i++) {
                         var tr = document.createElement('TR');


                         var td = document.createElement('TD');
                         td.appendChild(document.createTextNode(resposta.produtos[i].idproduto))
                         tr.appendChild(td);

                         var td = document.createElement('TD');
                         td.appendChild(document.createTextNode(resposta.produtos[i].codigo))
                         tr.appendChild(td);

                         var td = document.createElement('TD');
                         td.appendChild(document.createTextNode(resposta.produtos[i].descricao))
                         tr.appendChild(td);

                         var td = document.createElement('TD');
                         td.setAttribute('id', 'saldo')
                         var inpfield = document.createElement('INPUT');
                         inpfield.setAttribute('class', 'form-control');
                         if (resposta.produtos[i].quantidade > 0) {
                             inpfield.setAttribute("style", "background-color: #C0FFEE;text-align:center;");
                         }
                         else if (resposta.produtos[i].quantidade < 0) {
                             inpfield.setAttribute("style", "background-color: #DE5157;text-align:center;");
                         } else {
                             inpfield.setAttribute("style", "background-color: #EFFACE;text-align:center;");
                         }

                         inpfield.value = resposta.produtos[i].quantidade;
                         td.appendChild(inpfield);
                         tr.appendChild(td);


                         var td = document.createElement('TD');
                         var div = document.createElement('DIV');
                         div.className = 'row';
                         var div1 = document.createElement('DIV');
                         div1.className = 'col-xs-6 ';
                         var div2 = document.createElement('DIV');
                         div2.className = 'col-xs-6 ';


                         var icon1 = document.createElement("span");
                         icon1.className = "glyphicon glyphicon-record";
                         icon1.setAttribute('style', 'color:red;');
                         var icon2 = document.createElement("span");
                         icon2.className = "glyphicon glyphicon-menu-down";
                         div1.appendChild(icon1);
                         div2.appendChild(icon2);
                         div.appendChild(div1);
                         div.appendChild(div2);
                         td.appendChild(div);
                         tr.appendChild(td);

                         tbody.appendChild(tr);
//
                     }
                     table.setAttribute('class', 'table table-responsive table-striped table-hover');
                     $('#saldo > input').change(function () {
                         console.log("inside change event");
                     });
                 },
                 error: function (error) {
                     new PNotify({
                         title: 'Erro',
                         text: 'Falha na solicitação de dados.[_estoque_saldos]',
                         type: 'error',
                         styling: 'bootstrap3'
                     });
                 }
             });


         });
     </script>
 {% endblock %}

templates/default/page_blank.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">

    </div>
{% endblock %}

 {% block javascripts %}
 {% endblock %}

templates/default/page_blank_list.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h2>RH</h2>
                </div>
                <div class="title_right">
                    <a href="{{ path('EtiquetaAvulsa') }}" class="btn btn-success  active pull-right" role="button">Novo
                        Funcionário&nbsp;<span
                                class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Title</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

 {% block javascripts %}
 {% endblock %}

templates/default/page_etiqueta_produto.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Notas Fiscais</h2>
                            <a href="{{ path('EtiquetaAvulsa') }}" class="btn btn-primary btn-round active pull-right"
                               role="button">Etiquetas Avulsas&nbsp;<span
                                        class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            </a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <table data-order='[[ 0, "desc" ]]' class="table table-striped" id="TabelaNotas">
                                <thead>
                                <tr>
                                    <th>#ID</th>
                                    <th>Nota Fiscal</th>
                                    <th>Fornecedor</th>
                                    <th>Data</th>
                                    <th>Imprimir Etiqueta</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for nota in notas %}
                                    <tr>
                                        <th scope="row">{{ nota.idnf }}</th>
                                        <td>{{ nota.nota }}</td>
                                        <td class="text-uppercase">{{ nota.fornecedor }}</td>
                                        <td>{{ nota.data }}</td>
                                        <td style="text-align: center"><a
                                                    href="{{ path('ImprimirEtiqueta',{'nota':nota.idnf}) }}">
                                                <i class="fa fa-print" aria-hidden="true"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



{% block javascripts %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#TabelaNotas').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese-Brasil.json"
                },
            });
        });
    </script>
{% endblock %}

templates/default/page_etiqueta_vara_nf.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h3>Etiquetas de Varas por Notas Fiscais</h3>
                            {# <a href="{{ path('EtiquetaAvulsa') }}" class="btn btn-success  active pull-right" role="button">Etiquetas Avulsas&nbsp;<span #}
                            {# class="glyphicon glyphicon-plus" aria-hidden="true"></span> #}
                            {# </a> #}
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <table data-order='[[ 0, "desc" ]]' class="table table-striped" id="TabelaNotas">
                                <thead>
                                <tr>
                                    <th>#ID</th>
                                    <th>Nota Fiscal</th>
                                    <th>Fornecedor</th>
                                    <th>Data</th>
                                    <th>Imprimir Etiqueta</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for nota in notas %}
                                    <tr>
                                        <th scope="row">{{ nota.idnf }}</th>
                                        <td>{{ nota.nota }}</td>
                                        <td class="text-uppercase">{{ nota.fornecedor }}</td>
                                        <td>{{ nota.data }}</td>
                                        <td style="text-align: center"><a
                                                    href="{{ path('ImprimirEtiquetaVaraNF',{'nota':nota.idnf}) }}">
                                                <i class="fa fa-print" aria-hidden="true"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


 {% block javascripts %}
     <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
     <script>
         $(document).ready(function () {
             $('#TabelaNotas').DataTable({
                 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese-Brasil.json"
                 },
             });
         });
     </script>
 {% endblock %}

templates/default/page_imprimir_etiqueta_produto.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Etiqueta de Produto</h3>
                </div>

            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h5>Itens da Nota Fiscal - Número: {{ nota.numero }} - {{ nota.nome }}
                                - {{ nota.data }}</h5>
                            <a href="{{ path('EtiquetaAvulsa') }}" class="btn btn-primary btn-round active pull-right"
                               role="button">Etiquetas Avulsas&nbsp;<span
                                        class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            </a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            {% form_theme form 'bootstrap_3_layout_small.html.twig' %}
                            {{ form_start(form) }}
                            {{ form_errors(form) }}
                            <div class="table-responsive">
                                <table  class="table ">
                                    <thead>
                                    <tr>

                                        <th>Código</th>
                                        <th>Id</th>
                                        <th>Descrição Etiqueta</th>
                                        <th>Preço</th>
                                        <th>Quantidade</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for etiqueta in form.etiquetas %}

                                        <tr>
                                            <th scope="row">
                                                {{ form_row(etiqueta.codigo, { 'label':false, 'attr':{'readonly':'true','style':'max-width: 25ch'} }) }}</th>
                                            <td>{{ form_row(etiqueta.idProduto, {'label':false, 'attr':{'style':'width: 20ch'} }) }}</td>
                                            <td>{{ form_row(etiqueta.descEtiqueta, {'label':false, 'attr':{'style':'width: 60ch'} }) }}</td>
                                            <td>{{ form_row(etiqueta.preco, { 'label':false }) }}</td>
                                            <td>{{ form_row(etiqueta.qtde, { 'label':false, 'attr':{'style':'width: 15  ch'}}) }}</td>
                                        </tr>

                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <div class="checkbox text-right">
                                <label id="zerarlabel"><input id="zerarCheckBox" type="checkbox" value="">Zerar
                                    todos</label>
                            </div>
                            <div style="align-content: center">
                                {{ form_widget(form.Imprimir,{'label':'Imprimir Etiquetas'}) }}
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


 {% block javascripts %}
     <script>
         $("#zerarCheckBox").click(function (event) {

             $("input[name*='qtde']").each(function () {
                 $(this).val("0");

             });
             $("#zerarCheckBox").fadeOut(600, function () {
                 $(this).remove();
             });
             $("#zerarlabel").fadeOut(600, function () {
                 $(this).remove();
             });
         });
     </script>
 {% endblock %}

templates/default/page_sat_param.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('vendors/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css') }}"/>

{% endblock %}

{% block page_content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>SAT Configuração do Produto</h3>
                </div>
                {% form_theme form 'bootstrap_3_layout.html.twig' %}

                {{ form_start(form) }}
                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group date" data-provide="datepicker">
                            <input type="text" id="data" class="form-control" value="{{ data|date('d/m/Y') }}">
                            <span class="input-group-btn">
                      <button class="btn btn-default" type="button"
                              onclick="buscaData()">
                          <span class="fa fa-search"></span>
                      </button>
                    </span>
                        </div>
                    </div>
                </div>

            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        {% for message in app.flashes('notice') %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        {% for message in app.flashes('error') %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <div class="x_title">
                            <h2>Itens do Pedido</h2>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="table-responsive">
                                <table class="table table-condensed table-responsive">
                                    <thead>
                                    <tr>
                                        <th>Código</th>
                                        <th>Descrição</th>
                                        <th>Tributação</th>
                                        <th>Origem</th>
                                        <th>NCM</th>
                                        <th>PIS</th>
                                        <th>COFINS</th>
                                        <th>Simples</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for SATProduto in form.satprodutos %}

                                        <tr>
                                            <th scope="row">
                                                {{ form_row(SATProduto.codigo, { 'label':false, 'attr':{'readonly':'true','style':'max-width: 30ch'} }) }}</th>
                                            <td>{{ form_row(SATProduto.descricao, {'label':false, 'attr':{'readonly':'true','style':'width: 45ch'} }) }}</td>
                                            <td>{{ form_row(SATProduto.icms, {'label':false, 'attr':{'style':'width: 10ch'} }) }}</td>
                                            <td>{{ form_row(SATProduto.origem, {'label':false, 'attr':{'style':'width: 10ch'} }) }}</td>
                                            <td>{{ form_row(SATProduto.ncm, {'label':false, 'attr':{'style':'width: 15ch'} }) }}</td>
                                            <td>{{ form_row(SATProduto.pis, {'label':false, 'attr':{'style':'width: 8ch'} }) }}</td>
                                            <td>{{ form_row(SATProduto.cofins, {'label':false, 'attr':{'style':'width: 8ch'} }) }}</td>
                                            <td>{{ form_row(SATProduto.simplesCsosn, {'label':false, 'attr':{'style':'width: 8ch'} }) }}</td>
                                        </tr>

                                    {% endfor %}

                                    </tbody>
                                </table>

                                <div class="text-right">
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>

                            {{ form_end(form) }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

 {% block javascripts %}
     <script src="{{ asset('vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
     <script src="{{ asset('vendors/bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js') }}"></script>

     <script>
         $.fn.datepicker.defaults.format = "d/m/yyyy";
         $.fn.datepicker.defaults.language = "pt-BR"
         String.prototype.replaceAll = function(de, para){
             var str = this;
             var pos = str.indexOf(de);
             while (pos > -1){
                 str = str.replace(de, para);
                 pos = str.indexOf(de);
             }
             return (str);
         }

         function buscaData() {
             var novaData = document.getElementById('data').value;
             {#console.log({{ absolute_url(path) }});#}

             window.location.href = "/SAT/parametros/" + novaData.replaceAll("/","-");
         }
     </script>
 {% endblock %}